---
configure_osx: true

configure_homebrew: true
homebrew_installed_packages:
  - jq
  - git
  - gh
  - gpg
  - sqlite
  - nmap
  - wget
  - tree
  - neovim
  - lazygit
  - prettier
  - tmux
  - ansible
  - dockutil

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - arc
  - docker
  - firefox
  - firefox@nightly
  - google-chrome
  - google-chrome@canary
  - brave-browser
  - iterm2
  - zed
  - 1password-cli
  - 1password
  - raycast
  - kaleidoscope
  - blender
  - qgis
  - transmit
  - jordanbaird-ice
  - jupyterlab
  - utm
  - multipass
  - visual-studio-code
  - sublime-merge
  - boop
  - choosy
  - daisydisk
  - vlc

mas_uninstalled_apps: []
mas_installed_apps:
  - { id: 1423210932, name: "Flow" }
  - { id: 403504866, name: "PCalc" }
  - { id: 937984704, name: "Amphetamine" }
  - { id: 1425368544, name: "Timery" }
  - { id: 1592917505, name: "Noir" }
  - { id: 6444915884, name: "Ice Cubes" }
  - { id: 1352778147, name: "Bitwarden" }
  - { id: 1498546559, name: "SwitchGlass" }
  - { id: 1469995354, name: "Broadcasts" }
  - { id: 1630573891, name: "Switcheroo" }
  - { id: 1493996622, name: "Front and Center" }
  - { id: 1056643111, name: "Clocker" }
  - { id: 6454431289, name: "CrystalFetch" }
mas_upgrade_all_apps: false

configure_dock: true
dockitems_remove:
  - Launchpad
  - Messages
  - Maps
  - Freeform
  - FaceTime
  - Photos
  - Contacts
  - Music
  - Keynote
  - Numbers
  - Pages
  - TV
  - Notes
  - Reminders
  - Podcasts
  - "App Store"
dockitems_persist:
  - name: Safari
    path: "/Applications/Safari.app/"
    pos: 1
  - name: Safari Technology Preview
    path: "/Applications/Safari Technology Preview.app/"
    pos: 2
  - name: Mail
    path: "/Applications/Mail.app/"
    pos: 3
  - name: Calendar
    path: "/Applications/Calendar.app/"
    pos: 4
  - name: Terminal
    path: "/Applications/Utilities/Terminal.app/"
    pos: 5
  - name: System Settings
    path: "/Applications/System Settings.app/"
    pos: 6
